[package]
<<<<<<< HEAD
name = "gh-actions"
description = "learn github actions in rust"
=======
name = "fibbot2"
description = "It will run my rust project"
>>>>>>> 6d3c29a7f62dea56caf23d7498b6c7e06768c5b7
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
